# Generated by Django 4.0 on 2023-12-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_selectedtopic_customuser_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='condition',
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Topic',
            field=models.TextField(null=True),
        ),
    ]
